language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pip install -U -r test_requirements.txt --use-mirrors
script:
  - py.test --doctest-modules --pep8 rtkit -v --cov rtkit --cov-report term-missing
after_success:
  - pip install python-coveralls --use-mirrors
  - coveralls
