language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - pip install -r test_requirements.txt --use-mirrors
script:
  - pep8 --ignore=E501 rtkit
  - pyflakes -x W rtkit
  - py.test --doctest-modules rtkit -v